### ISSUE TITLE
No Apline Linux support

### ISSUE THREAD

**Issue by robolivable** [NeblioTeam/docker-nebliod#3]
When running:
```bash
sudo docker run -i -t --rm --name nebliod -v $HOME/neblio-data:/root/.neblio -p 6325:6325 neblioteam/nebliod
```
I'm getting the following:
```bash
standard_init_linux.go:211: exec user process caused "exec format error"
```
This is on a Raspberry Pi Alpine installation (Alpine `armhf` Version 3.11.6).

**Comment by nebliodev** [comment]
For raspberry pi you want the `neblioteam/nebliod-rpi` image. This one has been specially compiled for armhf architectures. The `neblioteam/nebliod` image is compiled for x86_64 so that is the image you would use on a regular (server/desktop) Alpine install. 

So you want to try:
`sudo docker run -i -t --rm --name nebliod -v $HOME/neblio-data:/root/.neblio -p 6325:6325 neblioteam/nebliod-rpi`
